# NAME: Jenny Zhan
# EMAIL: yqzhan@g.ucla.edu
# ID: 005139695

# NAME: Wenxuan Liu
# EMAIL: allenliux01@163.com
# ID: 805152602

default:
	gcc -o lab3a -g -Wall -Wextra lab3a.c
dist:
	tar -czvf lab3a-805152602.tar.gz lab3a.c README Makefile ext2_fs.h
clean:
	rm -f lab3a lab3a-805152602.tar.gz
