# NAME: Wenxuan Liu
# EMAIL: allenliux01@163.com
# ID: 805152602

# NAME: Jenny Zhan
# EMAIL: yqzhan@g.ucla.edu
# ID: 005139695
default: 
	rm -f lab3b
	ln lab3b.py lab3b
	chmod u+x lab3b

clean:
	rm -f lab3b-005139695.tar.gz lab3b

dist:
	tar -czvf lab3b-005139695.tar.gz lab3b.py README Makefile