#NAME: Wenxuan Liu
#EMAIL: allenliux01@163.com
#ID: 805152602
default: lab4b.c
	gcc -g -lm -lmraa -Wall -Wextra -o lab4b lab4b.c
check:
	./check.sh
clean:
	rm -f lab4b *.tar.gz
dist:
	tar -czvf lab4b-805152602.tar.gz check.sh Makefile README lab4b.c