#NAME: Wenxuan Liu
#EMAIL: allenliux01@163.com
#ID: 805152602
all: lab1a
lab1a: lab1a.c
	gcc -Wall -Wextra -g -o lab1a lab1a.c
clean:
	rm -f lab1a *.o *.tar.gz
dist:
	tar -czvf lab1a-805152602.tar.gz lab1a.c Makefile README
